package fireforget

// Module loaded, executed, and unloaded when execution ends, OR when directed by the loader.
//  Provides an IO pipe that can be used. Input is typically generated by the operator
//  Can read from pipe, and write responses to the same pipe.
